"use client";
import {useEffect,useRef,useState} from "react";
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis} from "recharts";
import {Bot,Download,LayoutDashboard,Menu as MenuIcon,PackageOpen,PlugZap,Plus,Search,Trash2,Upload,WalletCards,Pencil} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Switch} from "@/components/ui/switch";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from "@/components/ui/sidebar";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {calculate,recordSchema,rupees,RecordData} from "@/lib/model";
import {parseCSV,orderFromCSV,csvTemplate} from "@/lib/csv";
import {detectFeeAnomalies} from "@/lib/anomaly";
import {apiFetch} from "@/lib/supabase-client";
type View="Overview"|"Orders"|"Menu"|"Finance"|"Integrations"|"AI Insights";
const navigation=[{name:"Overview",icon:LayoutDashboard},{name:"Orders",icon:PackageOpen},{name:"Menu",icon:MenuIcon},{name:"Finance",icon:WalletCards},{name:"Integrations",icon:PlugZap},{name:"AI Insights",icon:Bot}] as const;
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"});
const isoToday=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Kolkata"}).format(new Date());
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Dashboard(){
 const [view,setView]=useState<View>("Overview"),[rows,setRows]=useState<RecordData[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState("");
 const [start,setStart]=useState(""),[end,setEnd]=useState(""),[draft,setDraft]=useState<any>(null),[deleting,setDeleting]=useState<RecordData|null>(null),[formError,setFormError]=useState(""),[pending,setPending]=useState<RecordData[]|null>(null),[ai,setAI]=useState(""),[aiBusy,setAIBusy]=useState(false);
 const file=useRef<HTMLInputElement>(null);
 async function refresh(){setLoading(true);try{const res=await apiFetch("/api/records");const json=await res.json();if(!res.ok)throw new Error(json.error);setRows(json.records);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load records")}finally{setLoading(false)}}
 useEffect(()=>{const d=isoToday();setStart(d.slice(0,8)+"01");setEnd(d);void refresh()},[]);
 const stats=calculate(rows,start,end);const feeAnomalies=detectFeeAnomalies(rows,start,end);const list=rows.filter(r=>r.kind===(view==="Menu"?"menu":view==="Finance"?"expense":"order")&&(r.kind==="menu"||r.date>=start&&r.date<=end)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
 async function save(records:RecordData[]){setBusy(true);try{const res=await apiFetch("/api/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({records})});const json=await res.json();if(!res.ok)throw new Error(json.error);setRows(old=>[...old.filter(x=>!records.some(n=>n.id===x.id)),...records]);toast.success(records.length===1?"Record saved":"Import saved");return true}catch(e){const m=e instanceof Error?e.message:"Save failed";setFormError(m);toast.error(m);return false}finally{setBusy(false)}}
 function add(kind:string){setFormError("");setDraft(kind==="menu"?{id:crypto.randomUUID(),kind,name:"",category:"Mains",price:0,cost:0,active:true}:kind==="expense"?{id:crypto.randomUUID(),kind,name:"",category:"Operations",date:isoToday(),amount:0}:{id:crypto.randomUUID(),kind,name:"",reference:"",partner:"Direct",date:isoToday(),gross:0,discount:0,refund:0,fee:0,food:0,packaging:0,status:"Delivered"})}
 async function submit(e:React.FormEvent){e.preventDefault();setFormError("");const parsed=recordSchema.safeParse(draft);if(!parsed.success){setFormError("Check all fields: use valid dates, positive amounts, and keep discounts + refunds within gross sales.");return}let record=parsed.data;if(record.kind==="order"){const matched=rows.find(r=>r.kind==="order"&&r.partner===record.partner&&r.reference===record.reference&&r.id!==record.id);if(matched){setFormError("This partner order reference already exists. Edit the existing order.");return}}
 if(await save([record]))setDraft(null)}
 async function remove(){if(!deleting)return;setBusy(true);try{const res=await apiFetch("/api/records?id="+encodeURIComponent(deleting.id),{method:"DELETE"});if(!res.ok)throw new Error("Delete failed. Try again.");setRows(old=>old.filter(x=>x.id!==deleting.id));setDeleting(null);toast.success("Record deleted")}catch(e){toast.error(String(e))}finally{setBusy(false)}}
 async function importFile(f:File){try{if(f.size>500000)throw new Error("CSV must be under 500 KB.");const parsed=parseCSV(await f.text());const data=parsed.map(orderFromCSV).map(r=>{if(r.kind!=="order")return r;const existing=rows.find(x=>x.kind==="order"&&x.partner===r.partner&&x.reference===r.reference);return existing?{...r,id:existing.id}:r});if(!data.length||data.length>500)throw new Error("Import between 1 and 500 orders.");const keys=new Set(data.map(r=>r.id));if(keys.size!==data.length)throw new Error("Duplicate partner/order references within this file.");setPending(data);setFormError("")}catch(e){toast.error(e instanceof Error?e.message:"Invalid CSV")}}
 async function askAI(){setAIBusy(true);setAI("");try{const r=await apiFetch("/api/insights",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({start,end})});const j=await r.json();if(!r.ok)throw new Error(j.error);setAI(j.text)}catch(e){setAI(e instanceof Error?e.message:"AI unavailable")}finally{setAIBusy(false)}}
 const daily=Array.from({length:Math.min(stats.days,62)},(_,i)=>{const d=new Date(Date.parse(end)-i*86400000).toISOString().slice(0,10);const s=calculate(rows,d,d);return {day:d.slice(5),revenue:s.revenue,profit:s.profit}}).reverse();
 return <SidebarProvider className="restaurant-app"><Sidebar className="restaurant-sidebar"><SidebarHeader><div className="brand"><i>S</i><div><b>ServeSync</b><span>Restaurant command center</span></div></div></SidebarHeader><SidebarContent><SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.name}><SidebarMenuButton isActive={view===n.name} onClick={()=>{setView(n.name);setQuery("")}}><n.icon/><span>{n.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="access-note">Private workspace<br/><b>Owner administration</b><p>Saved records. INR · India time.</p></div></SidebarContent></Sidebar>
 <main className="workspace"><header><div className="header-title"><SidebarTrigger/><div><p>YOUR RESTAURANT, IN ONE PLACE</p><h1>{view}</h1></div></div><button className="primary" disabled={loading||!!error} onClick={()=>add(view==="Menu"?"menu":view==="Finance"?"expense":"order")}><Plus size={18}/>Add {view==="Menu"?"item":view==="Finance"?"expense":"order"}</button></header>
 <div className="toolbar"><div className="dates"><label>From<input aria-label="From date" type="date" value={start} max={end} onChange={e=>setStart(e.target.value)}/></label><label>To<input aria-label="To date" type="date" min={start} max={isoToday()} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label className="search"><Search size={18}/><input aria-label="Search records" placeholder="Search records" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {error?<section className="notice" role="alert">{error}<button className="secondary" onClick={refresh}>Retry loading</button></section>:loading?<section className="notice" role="status">Loading your saved restaurant records…</section>:<>
 {view==="Overview"&&<div className="page"><section className="welcome"><div><span className="eyebrow">THE BIG PICTURE</span><h2>Know what your kitchen earns.</h2><p>{stats.orders?stats.orders+" orders recorded in this period. Your numbers below update with each saved order and expense.":"Your workspace is ready. Add an order or import a CSV to begin tracking real earnings."}</p><button onClick={()=>setView("Orders")}>Manage orders →</button></div><div className="food-art" role="img" aria-label="Paneer rice bowl"/></section><section className="metrics"><Metric title="Net sales" amount={stats.revenue} note="Gross − discounts − refunds"/><Metric title={stats.profit<0?"Operating loss":"Operating profit"} amount={stats.profit} note="After all recorded costs"/><Metric title="Profit margin" value={stats.margin.toFixed(1)+"%"} note="Operating profit / net sales"/><Metric title="Partner fees" amount={stats.fees} note="As entered per order"/></section><div className="two-col"><section className="panel"><Head title="Sales & profit" eyebrow="DAILY PERFORMANCE"/>{stats.orders?<div className="chart"><ResponsiveContainer><AreaChart data={daily}><CartesianGrid vertical={false} stroke="#ececec"/><XAxis dataKey="day"/><Tooltip formatter={(v)=>rupees(Number(v))}/><Area dataKey="revenue" name="Net sales" stroke="#ff633d" fill="#fff0e9"/><Area dataKey="profit" name="Operating profit" stroke="#168362" fill="transparent"/></AreaChart></ResponsiveContainer></div>:<Empty text="No orders in this date range."/ >}</section><section className="panel"><Head title="Channel performance" eyebrow="YOUR ORDER MIX"/>{["Swiggy","Zomato","Direct","ONDC",...new Set(rows.filter(r=>r.kind==="order").map(r=>r.partner).filter(p=>!["Swiggy","Zomato","Direct","ONDC"].includes(p)))].map(p=><div className="channel-row" key={p}><b>{p}</b><span>{rupees(calculate(rows.filter(r=>r.kind==="order"&&r.partner===p),start,end).revenue)}</span></div>)}</section></div><section className="insight"><div><span>30-DAY RUN-RATE ESTIMATE</span><h3>{stats.orders?rupees(stats.forecast):"Add orders to calculate a forecast"}</h3><p>Average daily operating profit over {stats.days} selected days × 30. Not AI-generated; not guaranteed. Record all costs before relying on this estimate.</p></div></section></div>}
 {(view==="Orders"||view==="Menu"||view==="Finance")&&<div className="page"><div className="title-row"><div><h2>{view==="Menu"?"Your menu":view==="Finance"?"Operating expenses":"All partner orders"}</h2><p>{view==="Finance"?"Record rent, salaries and other overheads here. Order food, packaging and platform fees belong on orders.":view==="Menu"?"Local menu control. Changes do not sync to delivery partners.":"Import normalized partner exports or enter orders manually."}</p></div>{view==="Orders"&&<button className="secondary" onClick={()=>file.current?.click()}><Upload size={17}/>Import CSV</button>}</div>
 {view==="Finance"&&<section className="finance-hero"><div><span>OPERATING PROFIT / LOSS</span><strong>{rupees(stats.profit)}</strong><p>{rupees(stats.revenue)} net sales − {rupees(stats.cost)} costs</p></div><div><span>30-DAY RUN RATE</span><strong>{stats.orders?rupees(stats.forecast):"—"}</strong><p>Linear estimate · no confidence score</p></div></section>}
 {view==="Menu"?<div className="menu-grid">{list.map(r=>r.kind==="menu"&&<article className="dish" key={r.id}><div className="dish-body"><div className="dish-title"><div><span>{r.category}</span><h3>{r.name}</h3></div><Edit record={r} edit={()=>{setDraft(r);setFormError("")}} remove={()=>setDeleting(r)}/></div><dl><div><dt>Price</dt><dd>{rupees(r.price)}</dd></div><div><dt>Food cost</dt><dd>{rupees(r.cost)}</dd></div><div><dt>Food margin</dt><dd>{r.price?((r.price-r.cost)/r.price*100).toFixed(1):"0"}%</dd></div></dl><div className="availability-row"><Switch aria-label={"Availability of "+r.name} checked={r.active} disabled={busy} onCheckedChange={active=>void save([{...r,active}])}/>{r.active?"Available":"Unavailable"}</div></div></article>)}</div>:<section className="panel"><Table><TableHeader><TableRow><TableHead>{view==="Orders"?"Order / channel":"Expense"}</TableHead><TableHead>Date</TableHead><TableHead>{view==="Orders"?"Gross / net sales":"Amount"}</TableHead><TableHead>{view==="Orders"?"Status":"Category"}</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{list.map(r=><TableRow key={r.id}><TableCell><b>{r.kind==="order"?r.reference:r.name}</b><small>{r.kind==="order"?r.partner+" · "+r.name:""}</small></TableCell><TableCell>{r.kind!=="menu"&&r.date}</TableCell><TableCell>{r.kind==="order"?<>{rupees(r.gross)}<small>{rupees(r.gross-r.discount-r.refund)} net</small></>:r.kind==="expense"?rupees(r.amount):""}</TableCell><TableCell>{r.kind==="order"?r.status:r.kind==="expense"?r.category:""}</TableCell><TableCell><Edit record={r} edit={()=>{setDraft(r);setFormError("")}} remove={()=>setDeleting(r)}/></TableCell></TableRow>)}</TableBody></Table></section>}
 {!list.length&&<Empty text={"No "+(view==="Menu"?"menu items":"records")+" yet. Use the Add button to create one."}/>}
 {view==="Finance"&&<section className="panel breakdown"><Head title="Profit calculation" eyebrow="NO HIDDEN DEDUCTIONS"/>{[["Gross sales",stats.gross],["Discounts",stats.discount],["Refunds",stats.refund],["Net sales",stats.revenue],["Partner fees",stats.fees],["Food cost",stats.food],["Packaging",stats.packaging],["Overheads",stats.overhead],["Operating profit / loss",stats.profit]].map(([k,v])=><div className="channel-row" key={k}><span>{k}</span><b>{rupees(Number(v))}</b></div>)}<p className="notice">Use sales excluding pass-through taxes. This is an operational estimate, not statutory accounting. Do not record the same cost both on an order and as an expense.</p><button className="secondary" onClick={()=>download("servesync-profit.csv","metric,INR\n"+Object.entries(stats).filter(([,v])=>typeof v==="number").map(([k,v])=>k+","+v).join("\n"))}><Download size={16}/>Export summary</button></section>}
 </div>}
 {view==="Integrations"&&<div className="page"><Head title="Bring every channel together" eyebrow="CONNECTIONS"/><p className="notice">No partner accounts are connected. Automatic order and menu synchronization needs a partner-specific integration and authorized access. CSV reporting works now using the template below.</p><div className="integration-grid">{["Swiggy","Zomato","ONDC","Other partner"].map((p,i)=><article key={p}><i style={{background:["#ff7a20","#e23744","#168362","#6958b4"][i]}}>{p[0]}</i><div><h3>{p}</h3><p>Live API integration pending</p></div><span className="available">Not connected</span></article>)}</div><section className="api-note"><PlugZap/><div><h3>CSV import is available</h3><p>Download the normalized template, copy your partner export into its columns, then upload it in Orders. Up to 500 rows. Existing matching partner + reference rows are updated only after confirmation.</p><button className="secondary" onClick={()=>download("servesync-orders-template.csv",csvTemplate)}><Download size={16}/>Download CSV template</button></div></section></div>}
 {view==="AI Insights"&&<div className="page"><section className="ai-hero"><i><Bot/></i><span>SERVESYNC INTELLIGENCE</span><h2>A clearer view of your restaurant.</h2><p>Calculated insights work now. Generative analysis requires a configured AI provider.</p></section><section className="recs"><article><em>01</em><div><span>CALCULATED · NOT AI</span><h3>{stats.orders?stats.profit<0?"Recorded costs exceed net sales":"Your recorded operating margin is "+stats.margin.toFixed(1)+"%":"Start with complete order records"}</h3><p>Profit is only as complete as your recorded fees, refunds, food costs and overheads.</p></div></article><article><em>02</em><div><span>FORECAST METHOD</span><h3>{stats.orders?rupees(stats.forecast)+" over 30 days":"Not enough records for a forecast"}</h3><p>Selected-period daily profit × 30. Assumes the same sales rate and cost mix. No seasonal adjustment.</p></div></article></section><section className="panel ai-output"><h3>Unusual partner fees</h3><p>Compared with other orders from the same partner in this date range. Uses a median and median absolute deviation; requires at least eight non-cancelled orders. Review flagged fees against your partner statement before changing anything.</p>{feeAnomalies.length?feeAnomalies.map(a=><div className="channel-row" key={a.partner+":"+a.reference+":"+a.date}><span>{a.partner} · {a.reference} · {a.date}</span><b>{(a.rate*100).toFixed(1)}% vs typical {(a.baseline*100).toFixed(1)}%</b></div>):<p role="status">No unusual fees detected in the selected period, or there are fewer than eight comparable orders per partner.</p>}</section><section className="panel ai-output"><h3>Generate a business analysis</h3><p>Send this period’s aggregated figures—not customer details—to the configured AI provider. Suggestions require your review and never change prices automatically.</p><button className="primary" disabled={aiBusy||!stats.orders} onClick={askAI}>{aiBusy?"Analyzing…":"Generate AI analysis"}</button>{ai&&<p role="status" style={{whiteSpace:"pre-wrap"}}>{ai}</p>}</section></div>}
 </>}
 <input ref={file} type="file" hidden accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value=""}}/>
 </main>
 <Dialog open={!!draft} onOpenChange={o=>{if(!o&&!busy)setDraft(null)}}><DialogContent className="editor"><DialogTitle>{draft?"Edit "+draft.kind:"Record"}</DialogTitle><DialogDescription>Saved securely to your private workspace. Amounts are in INR.</DialogDescription>{draft&&<form onSubmit={submit}><div className="form-grid">{Object.entries(draft).filter(([k])=>!["id","kind","active","status"].includes(k)).map(([k,v])=><label className="field" key={k}><span>{({gross:"Gross sales (excl. tax)",food:"Food cost",fee:"Partner fees",name:draft.kind==="order"?"Items / description":"Name"} as any)[k]||k[0].toUpperCase()+k.slice(1)}</span><input required min={typeof v==="number"?0:undefined} max={typeof v==="number"?100000000:undefined} step={typeof v==="number"?"0.01":undefined} maxLength={200} type={k==="date"?"date":typeof v==="number"?"number":"text"} value={String(v)} onChange={e=>setDraft({...draft,[k]:typeof v==="number"?(e.target.value===""?0:Number(e.target.value)):e.target.value})}/></label>)}</div>{draft.kind==="order"&&<label className="field"><span>Status</span><Select value={draft.status} onValueChange={status=>setDraft({...draft,status})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Delivered","Preparing","Ready","Cancelled"].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><small>For cancellations, enter any actual refunds and incurred costs explicitly.</small></label>}{formError&&<p className="form-error" role="alert">{formError}</p>}<button disabled={busy} className="primary wide" type="submit">{busy?"Saving…":"Save record"}</button></form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={o=>{if(!o&&!busy)setDeleting(null)}}><AlertDialogContent><AlertDialogTitle>Delete this record?</AlertDialogTitle><AlertDialogDescription>{deleting?.name} will be permanently removed and your totals recalculated.</AlertDialogDescription><AlertDialogCancel disabled={busy}>Keep record</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void remove()}}>Delete record</AlertDialogAction></AlertDialogContent></AlertDialog>
 <Dialog open={!!pending} onOpenChange={o=>{if(!o&&!busy)setPending(null)}}><DialogContent><DialogTitle>Review CSV import</DialogTitle><DialogDescription>{pending?.length} validated orders. {pending?.filter(r=>rows.some(x=>x.id===r.id)).length} existing orders will be replaced by matching partner and reference. No changes are saved yet.</DialogDescription><p>Check your dates, fees and food costs before confirming. Uploaded values are treated as actual figures.</p>{formError&&<p role="alert">{formError}</p>}<button className="primary" disabled={busy} onClick={async()=>{if(pending&&await save(pending))setPending(null)}}>{busy?"Importing…":"Confirm import"}</button></DialogContent></Dialog><Toaster richColors/>
 </SidebarProvider>
}
function Head({title,eyebrow}:{title:string;eyebrow:string}){return <div className="panel-head"><div><span>{eyebrow}</span><h3>{title}</h3></div></div>}
function Metric({title,amount,value,note}:{title:string;amount?:number;value?:string;note:string}){return <article className="metric"><div>{title}</div><strong>{value??rupees(amount??0)}</strong><p><span>{note}</span></p></article>}
function Empty({text}:{text:string}){return <div className="empty-state"><PackageOpen/><p>{text}</p></div>}
function Edit({record,edit,remove}:{record:RecordData;edit:()=>void;remove:()=>void}){return <div className="edit-buttons"><button aria-label={"Edit "+record.name} onClick={edit}><Pencil size={17}/></button><button aria-label={"Delete "+record.name} onClick={remove}><Trash2 size={17}/></button></div>}
